# _config.yaml - tell jekyll to do thy bidding
################################################################################

# automatically process changes to source files
auto: false

# Don't process or copy to _site
exclude: docroot, _notes, .idea

# Where to put the processed files
# destination: docroot